# Image made not by cloning the repository, but by local files
FROM node:latest AS build-stage
WORKDIR /app
COPY . /app/front-end
WORKDIR /app/front-end
RUN npm install --force && \
    npm run build

FROM nginx:alpine
COPY --from=build-stage /app/front-end/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

