name: Deploy to Remote Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies and Build
      run: |
        sudo npm install
        sudo npm run build

    - name: Deploy to Server
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        sshpass -e ssh -i <(echo "$SSH_KEY") $USERNAME@$HOST 'sudo cp -r /tmp/build/* /var/www/html && sudo systemctl restart nginx'

