export const COMMANDS = [
  { command: 'get the historical price of MSFT using polygon', tags: 'markets' },
  { command: 'get the latest news about Google and analyze their sentiment (1 - very positive, 0 - very negative)', tags: 'news' },
  { command: 'who is Michael Burry and why is he important for investors?', tags: 'knowledge' },
  { command: 'get future prices for VX', tags: 'derivatives' },
  { command: 'get last messages about AMZN from reddit', tags: 'news' },
  { command: 'get the current interest rates of central banks', tags: 'forex' },
  { command: 'get the top 3 queries related to Apple', tags: 'news' },
  { command: 'write some investment strategies for a bear market', tags: 'knowledge' },
  { command: 'get the short interest for BA', tags: 'markets' },
  { command: 'get trending articles', tags: 'news' },
  { command: 'get the latest cryptocurrency news', tags: 'news' },
  { command: 'get trailing dividend yield for BA', tags: 'markets' },
  { command: 'What is a margin call and how could we avoid it? Use the duck', tags: 'knowledge' },
  { command: 'get the best performing ETFs this year', tags: 'markets' },
  { command: 'get the balance sheets of Apple using polygon', tags: 'markets' },
  { command: 'get stocks overview for [ticker]', tags: 'markets' },
  { command: 'get the historical performance for ticker AMZN', tags: 'markets' },
  { command: 'get the latest IPOs', tags: 'markets' },
  { command: 'get historical data of gold prices', tags: 'forex' },
  { command: 'search the latest economic indicators using the duck', tags: 'news' },
  { command: 'get the latest bond yield rates', tags: 'forex' },
  { command: 'get the top 5 mutual funds in 2023', tags: 'markets' },
  { command: 'search the environmental, social, and governance score for TSLA using the duck', tags: 'markets' },
  { command: 'get NVDA\'s earnings before interest, taxes, depreciation, and amortization (EBITDA) using polygon', tags: 'markets' },
  { command: 'search economic calendar events using the duck', tags: 'news' },
  { command: 'get social sentiment analysis for RobinHood (HOOD) using the duck', tags: 'news' },
  { command: 'get recent analyst downgrades using the duck', tags: 'news' },
  { command: 'get a list of upcoming dividend payments using Nasdaq', tags: 'markets' },
];

export const TAGS = ['derivatives', 'forex', 'markets', 'news', 'knowledge'];
