#name: "Docker build test in PRs"
#on:
#  pull_request:
#    branches:
#      - main
#
#jobs:
#  docker-build:
#    name: "Build Docker image"
#    runs-on: ubuntu-latest
#
#    permissions:
#      contents: read
#      packages: write
#
#    steps:
#      - name: Free disk space
#        run: |
#          sudo swapoff -a
#          sudo rm -f /swapfile
#          sudo apt clean
#          docker rmi $(docker image ls -aq)
#          df -h
#
#      - name: Checkout repository to build machine
#        uses: actions/checkout@v2
#
#      - name: Build and push to Docker Hub
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: false
